Run rn app as background job

diff --git a/.github/workflows/tests-e2e.yml b/.github/workflows/tests-e2e.yml
--- a/.github/workflows/tests-e2e.yml
+++ b/.github/workflows/tests-e2e.yml
@@ -57,14 +57,30 @@ jobs:
 
       - name: Run tests
         run: |
-          if [ "${{ matrix.name }}" = "Test Next App" ]; then
+          if [ "${{ matrix.name }}" == "Test Next App" ]; then
             ${{ matrix.package_manager }} run test
-          elif [ "${{ matrix.name }}" = "Test Expo App" ]; then
-            timeout 60 ${{ matrix.package_manager }} run test
+          elif [ "${{ matrix.name }}" == "Test Expo App" ]; then
+            # Start the server in the background and capture its PID
+            ${{ matrix.package_manager }} run test &
+            PID=$!
+            # Wait for the server to be ready on port 8081 or timeout after 60 seconds
+            timeout 60 bash -c '
+              while ! echo > /dev/tcp/localhost/8081; do
+                echo "Waiting for server on port 8081..."
+                sleep 1
+              done
+              echo "Server on port 8081 is ready!"
+              kill -9 $PID  # Forcefully stop the server if it's ready
+              exit 0  # Exit successfully if the server was ready before timeout
+            '
+            if [ $? -ne 0 ]; then
+              echo "Failed to connect within 60s."
+              exit 1  # Exit with failure if the server wasn't ready in time
+            fi
           fi
         working-directory: ${{ matrix.directory }}
 
-      - if: ${{ failure() }}
+      - if: ${{ failure() }} && ${{ matrix.name == 'Test Next App' }}
         name: Upload Error Screenshot
         uses: actions/upload-artifact@v3
         with:
